# Promote ABI changes from warnings to build errors.
# Use together with abicheck-enable.conf:
#
#   bitbake -R <path>/abicheck-enable.conf \
#           -R <path>/abicheck-errors.conf <target>

ERROR_QA:append = " abi-changed"
WARN_QA:remove = " abi-changed"
